// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function HandleNoThanks() {
  return window['go']['main']['App']['HandleNoThanks']();
}

export function HandleRemindMeLater() {
  return window['go']['main']['App']['HandleRemindMeLater']();
}

export function ResetStartupSettings() {
  return window['go']['main']['App']['ResetStartupSettings']();
}

export function SubmitSurvey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitSurvey'](arg1, arg2, arg3, arg4, arg5);
}
