// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupStatus():Promise<string>;

export function HandleNoThanks():Promise<Record<string, any>>;

export function HandleRemindMeLater():Promise<Record<string, any>>;

export function ResetStartupSettings():Promise<Record<string, any>>;

export function SubmitSurvey(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<Record<string, any>>;
